//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.elfmission.WindowsApps.ImageSplitter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.elfmission.WindowsApps.ImageSplitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap application_view_tile {
            get {
                object obj = ResourceManager.GetObject("application_view_tile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap asterisk_orange {
            get {
                object obj = ResourceManager.GetObject("asterisk_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap folder_picture {
            get {
                object obj = ResourceManager.GetObject("folder_picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap FullScreenImage {
            get {
                object obj = ResourceManager.GetObject("FullScreenImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   4ビットカラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_CMB_COLOR_DEPTH_04 {
            get {
                return ResourceManager.GetString("ImageSplitter_CMB_COLOR_DEPTH_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8ビットカラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_CMB_COLOR_DEPTH_08 {
            get {
                return ResourceManager.GetString("ImageSplitter_CMB_COLOR_DEPTH_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16ビットカラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_CMB_COLOR_DEPTH_16 {
            get {
                return ResourceManager.GetString("ImageSplitter_CMB_COLOR_DEPTH_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   24ビットカラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_CMB_COLOR_DEPTH_24 {
            get {
                return ResourceManager.GetString("ImageSplitter_CMB_COLOR_DEPTH_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32ビットカラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_CMB_COLOR_DEPTH_32 {
            get {
                return ResourceManager.GetString("ImageSplitter_CMB_COLOR_DEPTH_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置： 画面下▼　文字： ← 左 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_CMB_FILE_NAME_POS_BOTTOM_LEFT {
            get {
                return ResourceManager.GetString("ImageSplitter_CMB_FILE_NAME_POS_BOTTOM_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置： 画面下▼　文字： 右 → に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_CMB_FILE_NAME_POS_BOTTOM_RIGHT {
            get {
                return ResourceManager.GetString("ImageSplitter_CMB_FILE_NAME_POS_BOTTOM_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置： 画面上▲　文字： ← 左 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_CMB_FILE_NAME_POS_TOPLEFT {
            get {
                return ResourceManager.GetString("ImageSplitter_CMB_FILE_NAME_POS_TOPLEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置： 画面上▲　文字： 右 → に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_CMB_FILE_NAME_POS_TOPRIGHT {
            get {
                return ResourceManager.GetString("ImageSplitter_CMB_FILE_NAME_POS_TOPRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したフォルダは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_ERR_IMAGE_FOLDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ImageSplitter_ERR_IMAGE_FOLDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアプリケーションの実行にはWindows Vista以降が必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_ERR_VERSION_UNMATCH {
            get {
                return ResourceManager.GetString("ImageSplitter_ERR_VERSION_UNMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一括処理が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_INF_FINISHED_BATCH {
            get {
                return ResourceManager.GetString("ImageSplitter_INF_FINISHED_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個のイメージファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_INF_IMAGE_FILE_COUNT {
            get {
                return ResourceManager.GetString("ImageSplitter_INF_IMAGE_FILE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}はすでに起動しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_INF_SAME_APP_EXISTED {
            get {
                return ResourceManager.GetString("ImageSplitter_INF_SAME_APP_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビューワー画面を終了してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSplitter_QES_CLOSE_VIEWER_FORM {
            get {
                return ResourceManager.GetString("ImageSplitter_QES_CLOSE_VIEWER_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap layers_map {
            get {
                object obj = ResourceManager.GetObject("layers_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap size_horizontal {
            get {
                object obj = ResourceManager.GetObject("size_horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap size_vertical {
            get {
                object obj = ResourceManager.GetObject("size_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
