//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.elfmission.WindowsApps.ImageSplitter.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.elfmission.WindowsApps.ImageSplitter.Plugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   除去する中心線の幅は偶数を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_CENTER_WIDTH_IS_NOT_EVEN {
            get {
                return ResourceManager.GetString("ERR_CENTER_WIDTH_IS_NOT_EVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先フォルダを設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_SAVED_FOLDER_IS_BLANK {
            get {
                return ResourceManager.GetString("ERR_SAVED_FOLDER_IS_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先フォルダが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_SAVED_FOLDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_SAVED_FOLDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap MenuImage {
            get {
                object obj = ResourceManager.GetObject("MenuImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ページ分割... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先に同名のフォルダが既に存在します。続行してよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QES_SAVED_DIRECTORY_EXISTS {
            get {
                return ResourceManager.GetString("QES_SAVED_DIRECTORY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページ分割設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingFormTitle {
            get {
                return ResourceManager.GetString("SettingFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap splitType1_2 {
            get {
                object obj = ResourceManager.GetObject("splitType1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap splitType2_1 {
            get {
                object obj = ResourceManager.GetObject("splitType2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap splitVerti1_2 {
            get {
                object obj = ResourceManager.GetObject("splitVerti1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap splitVerti2_1 {
            get {
                object obj = ResourceManager.GetObject("splitVerti2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
